# config
cover: /img/bg_img.jpg
# logo: /img/logo.png
top_saying:
#- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
  - content: 大圣次去何为？
  - content: 踏碎凌霄
  - content: 若一去不回？
  - content: 那便不去了
# bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More

# rss: /atom.xml

highlightjs: vs

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml
#Categories
categories:
  - name: Flutter
    posts:
      - name: flutter for web
        path: /post/flutterForWeb
  - name: React
    posts:
      - name: react-router刷新404 nginx配置
        path: /post/reactRouterNginx
  - name: Js
    posts:
      - name: 视频切片转m3u8
        path: /post/videoToM3U8
      - name: 一个移动端翻页的封装
        path: /post/likeSwiper
  # - name: Node
  #   posts:
  #     - name:
  - name: DB
    posts:
      - name: centos 安装mysql8 以及常用sql语句
        path: /post/centOsInstallMysql
      - name: mac Mysql8密码
        path: /post/macMysql8Password
  - name: Nginx
    posts:
      - name: react-router刷新404 nginx配置
        path: /post/reactRouterNginx
      - name: Linux下安装Nginx
        path: /post/installNginxLinux
#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/MonkeyInWind
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
